# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WF5oCes3JY30ziQ87TM-DOJpNVrwnp6e
"""

name=input("Enter username:")
tickettype=str(input("Enter Ticket type [regular=500,VIP=1000]:"))
quantity=int(input("number of tickets:").lower())
if tickettype=="regular":
 total=500*quantity
elif tickettype=="vip":
 total=1000*quantity
else:
 print("invalid ticket type")

if total>3000:
  print("you recevied a discount")
  discount=total*10/100
  print("total=",total)
  print("discount=",discount)
  total=total-discount
  print("your new total is:",total)
else:
      print("your total is:")

